# Generated by Django 2.1.7 on 2019-08-07 13:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('card_id', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')])),
                ('balance', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_thru', models.DateTimeField(default=datetime.datetime(2020, 8, 6, 13, 48, 5, 511214, tzinfo=utc))),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')])),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PinSaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')])),
                ('new_pin', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')])),
                ('operation', models.BooleanField(default=True)),
                ('value', models.BigIntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_balance', models.BigIntegerField(default=0)),
            ],
        ),
    ]
