# Generated by Django 2.1.7 on 2019-08-09 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinsaver',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='valid_thru',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 15, 6, 39, 825253, tzinfo=utc)),
        ),
    ]
